### ISSUE TITLE
Schema doesn't contain "settings" table?

### ISSUE THREAD

**Issue by bradparks** [noahflk/railtrack#82]
Hey there... I have setup and can run the app locally, but don't seem to be able to get the DB setup correctly.

I tried running the `supabase.sql` file, but it didnt seem to take, and then when I run the app, it's looking for a settings table that isn't in the sql file either.

Any suggestions? Note I can login using Google, and am at the dashboard when this failure happens

Note I think the major thing is that the sql file doesn't even contain a `settings` table?

`The table `public.Settings` does not exist in the current database.`

Note I had previously tried running the supabase.sql against the db in supabase, and it failed as well (because the table/foreign key already exist)

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/185477/215334766-2b9789c3-435c-421f-a296-40779fd3cd5e.png">

**Comment by noahflk** [comment]
I just tried setting up a new blank install. For me everything worked fine when following the steps in the README. I just tweaked them and the env-example file.

I think your issue is caused by running the `supabase.sql` file before pushing the Prisma schema.

Try purging the Supabase DB and then running the Prisma command again. That will create a settings table. You shouldn't have to touch the `supabase.sql` file unless you need Logsnag notifications for sign ups.

Let me know if that doesn't fix it!
