### ISSUE TITLE
Bug: Cannot add a journey

### ISSUE THREAD

**Issue by TAKANOME-DEV** [noahflk/railtrack#89]
Hey @noahflk, love this project very much :100: Clean and nice design :fire: :rocket:  Good job :clap:

I hit an issue when trying to add a journey.

![Screenshot from 2023-02-14 07-33-45](https://user-images.githubusercontent.com/79809121/218669645-26ca475a-4abc-4d9b-88aa-f4fcfc1b4e19.png)
| Network - Headers | Network - Response |
| --- | --- |
|![Screenshot from 2023-02-14 07-34-16](https://user-images.githubusercontent.com/79809121/218669914-8d0452b1-d604-4486-8764-76e4ede1acfc.png)|![Screenshot from 2023-02-14 07-34-22](https://user-images.githubusercontent.com/79809121/218669866-8eb955c1-8a66-428b-86bb-a507d8e46cbd.png)|

**Comment by noahflk** [comment]
Hi @TAKANOME-DEV 

Thanks for the kind words and the bug report. If you're curious what caused it:

The journey you selected includes a walk from Chur, Amselweg to Chur Main Station. However, the Train Data API I use only shows this walk journey (instead of using a bus) at some very specific search times.

That's why my server couldn't find the journey when trying to add it. To fix it, I had to use the precise departure time of the journey you're trying to save.

**Comment by TAKANOME-DEV** [comment]
Hi 👋 
Thanks for taking the time to fix this issue. Really appreciate it ✌️
